FileVersion = 1
Projects = {Ariyana_beef = {Path = "."}, t01Init = {Path = "tests/t01Init"}, t02Network = {Path = "tests/t02Network"}, t02NetworkClient = {Path = "tests/t02NetworkClient"}}

[Workspace]
StartupProject = "t02NetworkClient"
