FileVersion = 1

[Project]
Name = "Ariyana_beef"
TargetType = "BeefLib"
StartupObject = "Ariyana_beef.Program"
DefaultNamespace = "ari"

[Configs.Debug.Win64]
CLibType = "Static"
BeefLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)/dist/cari.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/*.dll\")"]
